"""Add DSS modules

Revision ID: 21d8482dd572
Revises: fd1263898ed4
Create Date: 2026-04-29 02:32:04.495444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d8482dd572'
down_revision: Union[str, Sequence[str], None] = 'fd1263898ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_data',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('predicted', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecast_data_forecast_id'), 'forecast_data', ['forecast_id'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_volunteer_profiles_profile_id'), 'volunteer_profiles', ['profile_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_table('beneficiary_aid',
    sa.Column('aid_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('quantity_received', sa.Float(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.beneficiary_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ),
    sa.PrimaryKeyConstraint('aid_id')
    )
    op.create_index(op.f('ix_beneficiary_aid_aid_id'), 'beneficiary_aid', ['aid_id'], unique=False)
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('donation_type', sa.String(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_index(op.f('ix_donations_donation_id'), 'donations', ['donation_id'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    op.create_table('program_volunteers',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_program_volunteers_assignment_id'), 'program_volunteers', ['assignment_id'], unique=False)
    op.create_table('resource_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('from_region_id', sa.Integer(), nullable=True),
    sa.Column('to_region_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_region_id'], ['regions.region_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ),
    sa.ForeignKeyConstraint(['to_region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_resource_transactions_transaction_id'), 'resource_transactions', ['transaction_id'], unique=False)
    op.create_table('volunteer_skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_volunteer_skills_skill_id'), 'volunteer_skills', ['skill_id'], unique=False)
    op.add_column('beneficiaries', sa.Column('need_type', sa.String(), nullable=True))
    op.add_column('beneficiaries', sa.Column('priority_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiaries', 'priority_level')
    op.drop_column('beneficiaries', 'need_type')
    op.drop_index(op.f('ix_volunteer_skills_skill_id'), table_name='volunteer_skills')
    op.drop_table('volunteer_skills')
    op.drop_index(op.f('ix_resource_transactions_transaction_id'), table_name='resource_transactions')
    op.drop_table('resource_transactions')
    op.drop_index(op.f('ix_program_volunteers_assignment_id'), table_name='program_volunteers')
    op.drop_table('program_volunteers')
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_donations_donation_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_beneficiary_aid_aid_id'), table_name='beneficiary_aid')
    op.drop_table('beneficiary_aid')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_volunteer_profiles_profile_id'), table_name='volunteer_profiles')
    op.drop_table('volunteer_profiles')
    op.drop_index(op.f('ix_forecast_data_forecast_id'), table_name='forecast_data')
    op.drop_table('forecast_data')
    # ### end Alembic commands ###
