"""Initial migration

Revision ID: fd1263898ed4
Revises: 
Create Date: 2026-04-26 04:41:34.561877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1263898ed4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('population_served', sa.Integer(), nullable=True),
    sa.Column('coordinates_lat', sa.Float(), nullable=True),
    sa.Column('coordinates_lng', sa.Float(), nullable=True),
    sa.Column('transport_cost_zone', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=False)
    op.create_index(op.f('ix_regions_region_name'), 'regions', ['region_name'], unique=False)
    op.create_table('resources',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=True),
    sa.Column('resource_type', sa.Enum('consumable', 'reusable', 'financial', 'human', name='resourcetypeenum'), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('minimum_threshold', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resources_resource_id'), 'resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_name'), 'resources', ['resource_name'], unique=False)
    op.create_table('region_demand_snapshots',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('resource_category', sa.String(), nullable=True),
    sa.Column('demand_quantity', sa.Float(), nullable=True),
    sa.Column('supply_quantity', sa.Float(), nullable=True),
    sa.Column('shortage_quantity', sa.Float(), nullable=True),
    sa.Column('surplus_quantity', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_region_demand_snapshots_snapshot_id'), 'region_demand_snapshots', ['snapshot_id'], unique=False)
    op.create_table('resource_inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('quantity_available', sa.Float(), nullable=True),
    sa.Column('quantity_committed', sa.Float(), nullable=True),
    sa.Column('quantity_reserved', sa.Float(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('last_restocked_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_resource_inventory_inventory_id'), 'resource_inventory', ['inventory_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'program_manager', 'data_entry', 'volunteer', 'donor', name='roleenum'), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('vulnerability_index', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_index(op.f('ix_beneficiaries_beneficiary_id'), 'beneficiaries', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_full_name'), 'beneficiaries', ['full_name'], unique=False)
    op.create_table('dss_recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('beneficiary_priority', 'resource_reallocation', 'program_flag', 'program_scale', 'donor_retention', 'volunteer_gap', name='recommendationtypeenum'), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='severityenum'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('actioned_by', sa.Integer(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_dss_recommendations_recommendation_id'), 'dss_recommendations', ['recommendation_id'], unique=False)
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.Column('program_type', sa.Enum('basic_needs', 'health', 'education', name='programtypeenum'), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'flagged', 'paused', 'closed', name='programstatusenum'), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('budget_spent', sa.Float(), nullable=True),
    sa.Column('target_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index(op.f('ix_programs_program_id'), 'programs', ['program_id'], unique=False)
    op.create_index(op.f('ix_programs_program_name'), 'programs', ['program_name'], unique=False)
    op.create_table('whatif_simulations',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('run_by', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('input_parameters_json', sa.JSON(), nullable=True),
    sa.Column('output_results_json', sa.JSON(), nullable=True),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_index(op.f('ix_whatif_simulations_simulation_id'), 'whatif_simulations', ['simulation_id'], unique=False)
    op.create_table('beneficiary_program_enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dropout_reason', sa.String(), nullable=True),
    sa.Column('last_aid_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.beneficiary_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_beneficiary_program_enrollments_enrollment_id'), 'beneficiary_program_enrollments', ['enrollment_id'], unique=False)
    op.create_table('vulnerability_assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('income_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('shelter_score', sa.Float(), nullable=True),
    sa.Column('food_security_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('composite_vulnerability_index', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.beneficiary_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_vulnerability_assessments_assessment_id'), 'vulnerability_assessments', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_assessments_assessment_id'), table_name='vulnerability_assessments')
    op.drop_table('vulnerability_assessments')
    op.drop_index(op.f('ix_beneficiary_program_enrollments_enrollment_id'), table_name='beneficiary_program_enrollments')
    op.drop_table('beneficiary_program_enrollments')
    op.drop_index(op.f('ix_whatif_simulations_simulation_id'), table_name='whatif_simulations')
    op.drop_table('whatif_simulations')
    op.drop_index(op.f('ix_programs_program_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_program_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_dss_recommendations_recommendation_id'), table_name='dss_recommendations')
    op.drop_table('dss_recommendations')
    op.drop_index(op.f('ix_beneficiaries_full_name'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_beneficiary_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resource_inventory_inventory_id'), table_name='resource_inventory')
    op.drop_table('resource_inventory')
    op.drop_index(op.f('ix_region_demand_snapshots_snapshot_id'), table_name='region_demand_snapshots')
    op.drop_table('region_demand_snapshots')
    op.drop_index(op.f('ix_resources_resource_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_regions_region_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
